### ISSUE TITLE
Signature mismatch in Shop-in-Shop payment

### ISSUE THREAD

**Issue by misterjoonas** [CheckoutFinland/psp-api#16]
I tired to make a Shop-in-Shop test payment with the following payload:
```yaml
{
  "stamp": "1536914138",
  "reference": "101",
  "amount": 100,
  "items": [
    {
      "unitPrice": 100,
      "units": 1,
      "vatPercentage": 24,
      "productCode": "#1234",
      "deliveryDate": "2018-09-14",
      "stamp": "1536914138",
      "reference": "101",
      "merchant": "695861",
      "commission": {
        "merchant": "695874",
        "amount": 10
      }
    }
  ],
  "customer": {
    "email": "test.person@example.org"
  },
  "redirectUrls": {
    "success": "https://local.project.fi/en/checkoutfi/test/checkout/complete",
    "cancel": "https://local.project.fi/en/checkoutfi/test/checkout/cancel"
  },
  "currency": "EUR",
  "language": "EN"
}
```

but I got a signature mismatch. To me it seems that everything else should be the same as in normal payment except for the extra fields in the items object and the `checkout-account` value in the header which I was testing with 695874. Is there something missing?
