### ISSUE TITLE
Add Provider name field when listing providers

### ISSUE THREAD

**Issue by mpesari** [CheckoutFinland/psp-api#46]
I think it would be useful (for labels, tooltips, alt hints etc) to return the `name` field for every provider when listing providers:

https://checkoutfinland.github.io/psp-api/#/?id=list-providers

The provider names are only returned when an order is created:

https://checkoutfinland.github.io/psp-api/#/examples?id=response

**Comment by loueranta** [comment]
Hi, the API should return `name` field for providers. 

Here's a snippet from [the full API specs](https://checkoutfinland.github.io/psp-api/checkout-psp-api.yaml):

```
    BasePaymentMethodProvider:
      type: object
      required:
      - name
      - icon
      - group
      - svg
      properties:
        name:
          type: string
          example: Osuuspankki
          description: Name of the payment method
```

Please let me know if you are not getting this information from the API.
